# general:
mode: analyze_cost
techdata_dir: 'data/tech/basic/'
techdata_files:
- basic_chemicals
projects_file: 'config/projects_test.csv'
do_overwrite_project_start_year: True
project_start_year_overwrite: 2025
ccfd_duration: 20
default_wacc: 0.06

#output
show_figures: True
show_figs_in_browser: True
output_dir: 'output/'
save_figures: False
crop_figures: True

# scenarios
scenarios_dir: 'data/scenarios/basic/'
scenarios_actual:
  free_allocations: ''
  prices:
    Electricity: 'Agora: konservativ'
    CO2: 'PIKExpertGuess-CO2'
    Natural Gas: '40 steady'
    Hydrogen: 'PIKExpertGuess-H2'
    Coking Coal: '100 steady'
    Injection Coal: '70 steady'
    Iron Ore: 'Eisenerz Agora'
    Scrap Steel: 'Zero_Dummy_Scrap'
    DRI-Pellets: 'DRI-Pellets Agora'
    Naphta: 'Naphta a)'
