# general:
mode: analyze_cost
techdata_dir: 'data/tech/basic/'
techdata_files:
- basic_chemicals
- cement
- glass_and_ceramics
- other_industries
- steel
- steel_dri
- scrap_steel
projects_file: 'config/projects.csv'
do_overwrite_project_start_year: True
project_start_year_overwrite: 2025
ccfd_duration: 20
default_wacc: 0.075

#output
show_figures: True
show_figs_in_browser: False
output_dir: 'output/'
save_figures: True
crop_figures: True

# scenarios
scenarios_dir: 'data/scenarios/basic/'
scenarios_actual:
  free_allocations: 'base_allocation'
  prices:
    Electricity: 'OL_scrap_base_elec' #ok
    CO2: 'PIKExpertGuess-CO2' #ok
    Natural Gas: 'OL_scrap_base_ngas' #ok
    Hydrogen: 'OL_scrap_base_hy' #ok
    Coking Coal: 'OL_scrap_base_ccoal' #ok
    Injection Coal: 'OL_scrap_base_icoal' #ok
    Iron Ore: 'OL_scrap_base_iore' #ok
    Scrap Steel: 'OL_scrap_base_scrap' #ok
    DRI-Pellets: 'DRI-Pellets Agora' #ok
    Naphta: 'Naphta a)' #ok
    Biomass: 'OL_scrap_base_biomass' #ok
